### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by affanshahid** [scalameta/metals-vscode#63] opened 2019-01-26 04:32 UTC
I am current using the ensime plugin which provides some code completion. I would love to switch to this, is auto-completion actively being worked on?

**Comment by olafurpg** [comment] 2019-01-26 08:32
Thanks for reporting! This is a duplicate of https://github.com/scalameta/metals-feature-requests/issues/8. Completions are not assigned for the latest v0.5 milestone but they may get into the v0.6 queue.

**Closed by olafurpg** 2019-01-26 08:32 UTC
