### ISSUE TITLE
Install metals extension crashes

### ISSUE THREAD

**Issue by aarcarons** [scalameta/metals-vscode#208] opened 2020-02-11 09:05 UTC
**Describe the bug**

Just trying to install Metals extension through the VS Code extensions menu. When I click installl some download appears to happen and at the end the following error message box is shown:

"The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted."

Tried uninstalling and reinstalling. But same outcome.

Hint: can it be related to accents in my user profile path? See the log below.
It should be "C:\Users\Adrià\..." instead of "C:\Users\Adri�\..."

**Installation:**

- Operating system: Windows
- VSCode version: 1.42.0
- VSCode extension version: 1.7.8
- Metals version: 0.8.0

**Additional context**
Java home: C:\Program Files\Java\jdk1.8.0_241
C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\lsp4j\org.eclipse.lsp4j\0.8.1\org.eclipse.lsp4j-0.8.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\thoughtworks\qdox\qdox\2.0.0\qdox-2.0.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\typesafe\config\1.4.0\config-1.4.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\plokhotnyuk\jsoniter-scala\jsoniter-scala-core_2.12\2.0.4\jsoniter-scala-core_2.12-2.0.4.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\sourcecode_2.12\0.2.0\sourcecode_2.12-0.2.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\h2database\h2\1.4.200\h2-1.4.200.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\upickle-core_2.12\0.9.7\upickle-core_2.12-0.9.7.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\github\soc\directories\11\directories-11.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\thesamet\scalapb\lenses_2.12\0.9.0\lenses_2.12-0.9.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\fastparse-utils_2.12\1.0.1\fastparse-utils_2.12-1.0.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\outr\perfolation-macros_2.12\1.1.5\perfolation-macros_2.12-1.1.5.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\checkerframework\checker-qual\2.10.0\checker-qual-2.10.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\openjdk\jol\jol-core\0.9\jol-core-0.9.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\trees_2.12\4.3.0\trees_2.12-4.3.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.12.10\scala-compiler-2.12.10.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\xtend\org.eclipse.xtend.lib\2.18.0\org.eclipse.xtend.lib-2.18.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\ujson_2.12\0.9.7\ujson_2.12-0.9.7.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\mdoc-interfaces\2.1.1\mdoc-interfaces-2.1.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\errorprone\error_prone_annotations\2.3.4\error_prone_annotations-2.3.4.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\wildfly\common\wildfly-common\1.5.2.Final\wildfly-common-1.5.2.Final.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna\4.5.2\jna-4.5.2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\zaxxer\nuprocess\1.2.4\nuprocess-1.2.4.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\net\java\dev\jna\jna-platform\4.5.2\jna-platform-4.5.2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\googlecode\java-diff-utils\diffutils\1.3.0\diffutils-1.3.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.16\interface-0.0.16.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\outr\scribe-slf4j_2.12\2.7.10\scribe-slf4j_2.12-2.7.10.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\outr\scribe-macros_2.12\2.7.10\scribe-macros_2.12-2.7.10.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\ch\epfl\scala\bsp4j\2.0.0-M4%2B10-61e61e87\bsp4j-2.0.0-M4%2B10-61e61e87.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\thesamet\scalapb\scalapb-runtime_2.12\0.9.0\scalapb-runtime_2.12-0.9.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-reflect\2.12.10\scala-reflect-2.12.10.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\lsp4j\org.eclipse.lsp4j.generator\0.8.1\org.eclipse.lsp4j.generator-0.8.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\pprint_2.12\0.5.8\pprint_2.12-0.5.8.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\xtext\org.eclipse.xtext.xbase.lib\2.18.0\org.eclipse.xtext.xbase.lib-2.18.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\fastparse_2.12\2.1.3\fastparse_2.12-2.1.3.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\wildfly\client\wildfly-client-config\1.0.0.Final\wildfly-client-config-1.0.0.Final.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\xtend\org.eclipse.xtend.lib.macro\2.18.0\org.eclipse.xtend.lib.macro-2.18.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\mtags_2.12.10\0.8.0\mtags_2.12.10-0.8.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jboss\logging\jboss-logging\3.4.0.Final\jboss-logging-3.4.0.Final.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-sbt\ipcsocket\ipcsocket\1.0.0\ipcsocket-1.0.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\parsers_2.12\4.3.0\parsers_2.12-4.3.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\fansi_2.12\0.2.8\fansi_2.12-0.2.8.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jboss\xnio\xnio-api\3.7.7.Final\xnio-api-3.7.7.Final.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\lsp4j\org.eclipse.lsp4j.jsonrpc.debug\0.8.1\org.eclipse.lsp4j.jsonrpc.debug-0.8.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\mtags-interfaces\0.8.0\mtags-interfaces-0.8.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\protobuf\protobuf-java\3.7.1\protobuf-java-3.7.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\lsp4j\org.eclipse.lsp4j.jsonrpc\0.8.1\org.eclipse.lsp4j.jsonrpc-0.8.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-dynamic_2.12\2.3.2\scalafmt-dynamic_2.12-2.3.2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\flywaydb\flyway-core\6.1.4\flyway-core-6.1.4.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\ch\epfl\scala\bloop-config_2.12\1.4.0-RC1\bloop-config_2.12-1.4.0-RC1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\guava\guava\28.2-jre\guava-28.2-jre.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scalap\2.12.10\scalap-2.12.10.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-collection-compat_2.12\2.1.3\scala-collection-compat_2.12-2.1.3.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven
.org\maven2\org\scalameta\scalameta_2.12\4.3.0\scalameta_2.12-4.3.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\eclipse\lsp4j\org.eclipse.lsp4j.debug\0.8.1\org.eclipse.lsp4j.debug-0.8.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\outr\perfolation_2.12\1.1.5\perfolation_2.12-1.1.5.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\ch\epfl\scala\bloop-launcher_2.12\1.4.0-RC1\bloop-launcher_2.12-1.4.0-RC1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-java8-compat_2.12\0.9.0\scala-java8-compat_2.12-0.9.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\scalafmt-interfaces\2.3.2\scalafmt-interfaces-2.3.2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\geny_2.12\0.5.0\geny_2.12-0.5.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\outr\scribe_2.12\2.7.10\scribe_2.12-2.7.10.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\semanticdb-scalac-core_2.12.10\4.3.0\semanticdb-scalac-core_2.12.10-4.3.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\methvin\directory-watcher\0.8.0\directory-watcher-0.8.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\metals_2.12\0.8.0\metals_2.12-0.8.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\fastparse_2.12\1.0.1\fastparse_2.12-1.0.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scalameta\common_2.12\4.3.0\common_2.12-4.3.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jboss\threads\jboss-threads\2.3.0.Beta2\jboss-threads-2.3.0.Beta2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jsoup\jsoup\1.12.1\jsoup-1.12.1.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\lz4\lz4-java\1.7.0\lz4-java-1.7.0.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\io\undertow\undertow-core\2.0.29.Final\undertow-core-2.0.29.Final.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\code\gson\gson\2.8.2\gson-2.8.2.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\jboss\xnio\xnio-nio\3.7.7.Final\xnio-nio-3.7.7.Final.jar;C:\Users\Adri�\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.12.10\scala-library-2.12.10.jar

Error: Could not find or load main class scala.meta.metals.Main
[Info  - 10:01:27] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
[Info  - 10:01:27] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
[Info  - 10:01:27] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
[Info  - 10:01:27] Connection to server got closed. Server will restart.
Error: Could not find or load main class scala.meta.metals.Main
[Error - 10:01:27] Connection to server got closed. Server will not be restarted.

**Comment by olafurpg** [comment] 2020-02-11 09:24
Thank you for reporting! The issue indeed seems to be caused by the accent character. I suspect the problem either lies on the vscode extension side or coursier.

**Comment by f-delahaye** [comment] 2020-03-21 12:58
Hi,
I'm facing the same problem.
When running  "java -jar coursier fetch -p org.scalameta:metals_2.12:0.8.3" from bash, the accents are not showing up correctly either.
They are however if the same command is run with -Dfile.encoding=UTF-8.

Looking at the coursier code, there are a few places where UTF-8 is hard coded. One of them, which may or may not be the root cause, is in coursier/cli/resolve/Dependencies.scala to call URLEncoder.encode. Per javadoc, it is in fact recommended to use UTF-8 as the encoding to avoid compatibility issues.

Is there anyway in metals to specify this -Dfile.encoding when calling coursier?

**Comment by tgodzik** [comment] 2020-03-21 16:07
Could you try adding it to the server properties? I think it's also used for the coursier fetch process. We could probably make this as a default.

**Comment by f-delahaye** [comment] 2020-03-23 06:11
Thanks for your help.

I added a server property at user level.
Output from coursier now looks correct e.g
`C:\Users\Frédéric\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\chuusai\shapeless_2.12\2.3.3\shapeless_2.12-2.3.3.jar
`
however, metals still fails with:

`[Info  - 06:56:54] Connection to server got closed. Server will restart.
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Users\Fr�d�ric
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
	at java.base/java.nio.file.Files.createDirectory(Files.java:689)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
	at java.base/java.nio.file.Files.createDirectories(Files.java:782)
	at scala.meta.internal.metals.MetalsLogger$.redirectSystemOut(MetalsLogger.scala:30)
	at scala.meta.internal.metals.GlobalTrace$.setup(GlobalTrace.scala:18)
	at scala.meta.metals.Main$.main(Main.scala:17)
	at scala.meta.metals.Main.main(Main.scala)
`

I was assuming that metals was using the output from Coursier to build its classpath, but maybe this is not the case ...
At this point, I wonder if it would make more sense to ask Coursier if they can do anything on their side?
Or can you think of something else to try in Metals?

**Comment by f-delahaye** [comment] 2020-03-28 17:19
Hi,

I have tried to run  scala.meta.metals.Main outside of VSCode / Metals / Coursier as follows:
`
java -Dfile.encoding=UTF-8 -cp "$CP" scala.meta.metals.Main
`
where CP includes :
`
org/scalameta/metals_2.12/0.8.3/metals_2.12-0.8.3.jar
io/github/soc/directories/11/directories-11.jar
org/scalameta/scalameta_2.12/4.3.6/scalameta_2.12-4.3.6.jar
outr/scribe_2.12/2.7.10/scribe_2.12-2.7.10.jar
org/scalameta/trees_2.12/4.3.6/trees_2.12-4.3.6.jar;
`

and it fails with the same error message.
Adding -Dsun.jnu.encoding=UTF-8 doesn't make any difference, property probably defaults to file.encoding

However, when compiling the latest version of io/github/soc/directories/Util.java and overriding the one from  io/github/soc/directories/11/directories-11.jar with my local version, it works.

The bug was probably fixed by this commit
https://github.com/soc/directories-jvm/commit/b6468f3b8a455bb90ec41ea579e04f716225f0f0#diff-fefdba6fdb964f5eaacffc4774798803

which forces UTF-8.

Upgrading Metals to  a more recent version of directories-jvm would probably help. But the latest release i could find is 11 which is the one currently used by metals and does not include the fix... 
Are you guys in contact with the directories-jvm team?

**Comment by tgodzik** [comment] 2020-03-30 12:48
Thanks for digging into it! I opened an issue asking about it: https://github.com/soc/directories-jvm/issues/31

**Closed** 2020-06-09 13:24 UTC
Labels: bug, help wanted
