### ISSUE TITLE
"test|debug test" disappears when using Scalafix with SemanticDB enabled

### ISSUE THREAD

**Issue by martin-konkol** [scalameta/metals-vscode#288] opened 2020-04-29 16:56 UTC
**Describe the bug**

The `test | debug test` options disappear when using SBT Scalafix plugin with SemanticDB enabled. The options reappear when the SemanticDB config is removed from the `build.sbt` and the project is reimported. Adding the plugin without actually enabling the SemanticDB does not cause the options to disappear.

**To Reproduce**
1. Add the SBT Scalafix plugin to your `plugins.sbt`
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.15")
```
2. Enable SemanticDB in your `build.sbt`
```
ThisBuild / semanticdbEnabled := true
ThisBuild / semanticdbVersion := scalafixSemanticdb.revision
```

**Expected behavior**

The `test | debug test` options should not be affected by adding/activating SBT plugins.

**Installation:**

- Operating system: Windows 10 (slow ring preview 10.0.19041), with WSL 2 on Ubuntu 18.04
- VSCode version: 1.44.2
- VSCode extension version: 1.8.6
- Metals version: 0.8.4

**Additional context**

Project is located inside the Ubuntu filesystem. Editor runs in the WSL remote mode.

**Comment by tgodzik** [comment] 2020-05-06 17:40
Thanks for reporting! It should work in the newest Metals version. This was most likely an issue that semanticDB version used by Metals was different than the one used by scalafix. Code lenses are generated using the information from semanticDB, which might have been different than expected.

If this happens again it will probably be best to enable the same semanticDB version as Metals uses as a workaround. Could you confirm if this is working for you in the newest release?

**Comment by martin-konkol** [comment] 2020-05-06 20:17
It doesn't seem to work with the latest version (1.9.0) and when I tried to override the plugin dependency to 4.3.10, there was an error in the build logs:
```
ERROR code navigation does not work for the file '...' because the SemanticDB file '...' doesn't exist. There can be many reasons for this error.
```

**Comment by tgodzik** [comment] 2020-05-07 07:37
> It doesn't seem to work with the latest version (1.9.0)

Do you maybe have a minimal `build.sbt`, that I can reproduce this on? When I was checking out the newest version, it did work with the settings you've shown, so not sure exactly what could be going on. 

>  and when I tried to override the plugin dependency to 4.3.10, there was an error in the build logs:
> 
> ```
> ERROR code navigation does not work for the file '...' because the SemanticDB file '...' doesn't exist. There can be many reasons for this error.
> ```

That error shows up if we the semanticdb files are not created. How did set the version exactly?

**Comment by tgodzik** [comment] 2020-05-07 07:56
Maybe this has something to with WSL? We read the semanticDB file by checking the `-P:semanticdb:targetroot:` option. Maybe the directory is no accessible if it's setup via sbt and Bloop doesn't have the same problem?

You can check in `.bloop/*.json` file how is the option set up and maybe you can set it manually in sbt to something we will sure will work?

**Comment by martin-konkol** [comment] 2020-05-07 18:57
Without the scalafix plugin and semanticDB, there is no `-P:semanticdb:targetroot` entry in any of the `.json` files. With the plugin and semanticDB enabled, the entries are following:
```
"-P:semanticdb:targetroot:<project root>/target/scala-2.13/meta"
"-P:semanticdb:targetroot:<project root>/target/scala-2.13/test-meta"
```

Both of those paths are inside the WSL 2, just like the rest of the project. I'm not sure that this is WSL related, since scalafix actually works fine when enabled and the `test | debug test` options work fine when scalafix is commented out. Both tools work on their own, just not at the same time. I cleaned the project completely to make sure there is no dirty state.

If we can't figure this out, it's not a big deal. Your vscode extension is awesome, so I'm happy to drop the scalafix plugin for now. I can easily live without it.

**Comment by tgodzik** [comment] 2020-05-07 20:32
> Without the scalafix plugin and semanticDB, there is no -P:semanticdb:targetroot entry in any of the .json files.

We add it automatically via Bloop if the setting is not set, otherwise we use the one that sbt set. I am a bit out of ideas what's going on there, there should be some exceptions or something.  I think I need to set something up on windows myself and check it out.

**Comment by tgodzik** [comment] 2020-05-07 20:40
You could also try a workaround maybe:
```
def isMetalsImport = System.getenv("METALS_ENABLED") == "true"
ThisBuild / semanticdbEnabled := { if (isMetalsImport) false else true }
ThisBuild / semanticdbVersion := scalafixSemanticdb.revision
```
we do add an additional env variable when running import.

**Comment by martin-konkol** [comment] 2020-05-07 20:58
That works! Thank you.

**Comment by tgodzik** [comment] 2022-01-20 15:41
Closing it for now, since the issue seems to have a workaround and this doesn't seem to happen too often.

**Closed by tgodzik** 2022-01-20 15:41 UTC
