### ISSUE TITLE
Metals starts even when project is not a scala project

### ISSUE THREAD

**Issue by DieBauer** [scalameta/metals-vscode#133] opened 2019-07-30 09:33 UTC
I'm using the metals vscode plugin, and it works great in my Scala / SBT projects. 

However I see that metals is being started even when the directory I open is not a scala project. 

This leads to the creation of a `.metals` directory in the project. 

**To Reproduce** Steps to reproduce the behavior:

- Open a directory that is not a scala project
- Metals is starting 
- .metals directory is created. 

**Expected behavior**

- No .metals directory, or starting of metals at all. 

**Installation:**

- Operating system: macOS
- VSCode version: 1.36.1
- VSCode extension version: 1.5.2
- Metals version: 0.7.0

**Comment by gabro** [comment] 2019-07-30 09:40
Hi @DieBauer, thanks for reporting!

The activation events for the extension are specified here:

https://github.com/scalameta/metals-vscode/blob/474809c3b70cba3a9d728ba1cc91e8d72ba7f76e/package.json#L44-L49

Is it possible that you're matching some of these?

If not, it would be really helpful if you could provide a minimal reproduction, so that I can try and reproduce the issue.

**Comment by DieBauer** [comment] 2019-08-06 19:04
I tried to reproduce the observed behaviour on new / empty folders, but I cannot. If this happens again, I'll re-open this issue.

**Comment by virtualdvid** [comment] 2019-08-10 23:32
I got this issue and now I have a ´.metals´ folder in my python projects.

**Comment by tgodzik** [comment] 2019-08-12 10:04
Do you have anything that matches any of the activasion events like shown by @gabro ?

> The activation events for the extension are specified here:
> 
> https://github.com/scalameta/metals-vscode/blob/474809c3b70cba3a9d728ba1cc91e8d72ba7f76e/package.json#L44-L49
>

**Comment by virtualdvid** [comment] 2019-08-12 17:00
yes I have configured by default that file with that list. I also isolated and independent folder for scala projects. and the folder `.metals` stills there on each of my projects.

**Comment by tgodzik** [comment] 2019-08-13 14:36
> yes I have configured by default that file with that list. I also isolated an independent folder for scala projects. and the folder `.metals` stills there on each of my projects.

Not sure I understand. VS Code will activate the extension only if a workspace contains any of the prerequisites that I pasted above. If any of those are matching then `.metals` will be present.

Do those Python projects contain any of those files or directories?

**Comment by virtualdvid** [comment] 2019-08-14 23:42
Hi @tgodzik, I have my Scala and Python projects totally isolated in their own folders. I also verified the Python projects and they don't have anything related with Scala.

**Comment by tgodzik** [comment] 2019-08-16 08:52
If so then it's a bug with VS Code, because Metals is only activated if you have either `build.sbt`. `build.sc`, `project/build.properties`, any `scala` directory or anything that identifies as language Scala.

Are you sure there is nothing from above? Do you have any open source repo or minimal example that you can reproduce the behavior?

**Comment by DieBauer** [comment] 2019-08-17 11:45
I ran into the same scenario: 

```

**Comment by tgodzik** [comment] 2019-08-17 12:14
The problem is that if nothing actually matches the activation events then it's not a Metals issue but VS Code one.

And without reproduction we cannot even exactly fix anything. I will close this issue until we have a reproduction.

**Comment by JamezMercier** [comment] 2020-01-21 14:43
Yes it is related if you have a `"metals.sbtScript": "C:\\Program Files (x86)\\sbt"` changing it to  `"metals.sbtScript": ""` fixed the problem for me. It is more related to that.

**Comment by lqhuang** [comment] 2020-02-02 15:41
@tgodzik I'm using the metals in vscode, and it works great in my Scala / SBT projects. Thanks a lot!
The same, when I switched to a `Python` project, `metals` starts then creates a `.metals` directory.

Here is my tree structure of project:
```plain
.
├── bert_client.py
├── db_models.py
├── difference.py
├── get_new_data.py
├── .git
| ..........
├── .gitignore
├── logs
│   ├── new_model
│   ├── new_model.2020-01-13.log
│   ├── new_model.2020-01-20.log
│   ├── stream_tweet_prediction.2019-12-31.log
│   ├── stream_tweet_prediction.2020-01-06.log
│   ├── stream_tweet_prediction.2020-01-13.log
│   ├── stream_tweet_prediction.2020-01-20.log
│   └── stream_tweet_prediction.txt
├── .metals
│   ├── metals.h2.db
│   └── metals.log
├── pred_rel_sent.py
├── README.md
├── recalc.py
├── requirements.txt
├── run_script_pred.py
├── run_script_pred.sh
├── scripts
│   ├── migrate_prediction.py
│   └── missing_time_distribution.py
├── select_new_user.py
├── sent2sent
├── sent_pred.service
├── src
├── tree.txt
└── .vscode
    └── settings.json

111 directories, 190 files
```
VS Code version: 

```
> code --version
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64
```

Metal version: 1.7.2

Or what other information would you need to find problems?

Thanks for your efforts:)
Regards.

**Comment by tgodzik** [comment] 2020-02-03 13:15
@lqhuang does this happen all the time even if you remove the `.metals` directory and reload?

The extension should not really be activated since I see nothing that matches the activationEvents.
It would nice to maybe try to copy dir and try deleting parts of it to locate the issue? Delete-> reload window.

**Comment by virtualdvid** [comment] 2020-02-03 14:51
@lqhuang I got the same problem. In my personal and job laptops. I ended up putting that folder in `.gitignore`. It's not a elegant solution but...

**Comment by tgodzik** [comment] 2020-02-03 15:21
@virtualdvid is it only on python projects that this happens? Do you have any open source repo that you can reproduce it with?

**Comment by virtualdvid** [comment] 2020-02-03 15:30
I just started a new workspace to learn `go` I only have the hello world file there and got the `.metals` folder:

![Code_fQlEpjd3B6](https://user-images.githubusercontent.com/33104726/73666033-fdf44f80-4656-11ea-8325-5bf83534d7ce.png)

**Comment by tgodzik** [comment] 2020-02-03 15:39
@virtualdvid I cannot reproduce unfortunately, but there should be more info in the VS Code logs

You need to go into output and then `Log (Extension Host)`:

![image](https://user-images.githubusercontent.com/3807253/73666849-b34cf480-46a3-11ea-8cd1-638ac7e48edc.png)

Is there anything indicating why Metals was activated?

**Comment by virtualdvid** [comment] 2020-02-03 15:56
Sure, The only log I got with metals was on Saturday but I was working on my python project I didn't even touch the Scala one. Actually I'm using eclipse for scala (sadly).

```
[2020-02-01 11:46:03.691] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals {"startup":true,"extensionId":{"value":"scalameta.metals","_lower":"scalameta.metals"},"activationEvent":"workspaceContainsTimeout:**/scala/**"}
[2020-02-01 11:46:03.692] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/myuser/.vscode/extensions/scalameta.metals-1.7.2/out/extension
```

**Comment by tgodzik** [comment] 2020-02-03 15:59
@virtualdvid Och, I think when it timeouts looking for pattern it activates the extension by default? :O 

`"activationEvent":"workspaceContainsTimeout:**/scala/**"`

**Comment by tgodzik** [comment] 2020-02-03 16:07
We might need to remove that pattern, VS code is not dealing well with it - but it will not be a good experience for gradle/maven, since people will need to open Scala files.

**Comment by lqhuang** [comment] 2020-02-04 08:07
@tgodzik It's interesting and very strange that I can't reproduce now after I deleted `.metals` and begin to find why by removing some files. It doesn't appear again. But I'm quite sure It's always happen in the past. So I must do something different.

Then I remembered that at that time, I just installed `Metals` extension and do not open any `scala` project yet, which means `Metals` probably has not initialized correctly. Once, I use `vscode` to open my `scala` project, `Metals` download its required packages, initialize itself, most importantly, then works normally in my `scala` project. After that, `.metals` doesn't appear again in other projects. I guess this is the reason make the difference.

So, base on previously mentioned, I agree with your thought that this is a `timeout` issue. Maybe you can use a clean installed `Metals` extension to reproduce problems?

**Comment by tgodzik** [comment] 2020-02-04 08:51
> @tgodzik It's interesting and very strange that I can't reproduce now after I deleted `.metals` and begin to find why by removing some files. It doesn't appear again. But I'm quite sure It's always happen in the past. So I must do something different.
> 
> Then I remembered that at that time, I just installed `Metals` extension and do not open any `scala` project yet, which means `Metals` probably has not initialized correctly. Once, I use `vscode` to open my `scala` project, `Metals` download its required packages, initialize itself, then most importantly, works normally in my `scala` project. After that, `.metals` doesn't appear again in other projects. I guess this is the reason make the difference.
> 
> So, base on previously mentioned, I agree with your thought that this is a `timeout` issue. Maybe you can use a clean installed `Metals` extension to reproduce problems?

Sounds like a good idea! But most likely we need to make the pattern smarter.

**Comment by gabro** [comment] 2020-02-04 21:37
Nice catch, this is indeed a vscode issue. See https://github.com/microsoft/vscode/issues/73656

I'm not sure of what's the best workaround

**Comment by tgodzik** [comment] 2020-02-05 10:34
We might try a couple of easier patterns that don't look so deep into the file tree like:
`*/scala/**`
`*/*/scala/**`
etc.

But timeouts might still happen.

**Comment by gabro** [comment] 2020-02-05 10:55
It's probably a dumb question, but there's no other indication that a project is a Maven/Gradle Scala project?

**Comment by tgodzik** [comment] 2020-02-05 10:58
> It's probably a dumb question, but there's no other indication that a project is a Maven/Gradle Scala project?

It's all defined either in `build.gradle` or `pom.xml`, but unfortunately we can't check what is contained in a file. And with those files it could also just be a java project.

**Comment by virtualdvid** [comment] 2020-02-07 19:56
Out of the solution you are trying to implement I just realized I can enable or disable extensions in vscode. I don't know why I wasn't doing that before. I just disabled Metals ext on my python workspaces.

**Comment by tgodzik** [comment] 2020-02-10 14:31
@virtualdvid I think that is the best option for now without regressing in the behavior. I believe this should really be fixed on the VS Code side.

**Closed by tgodzik** 2020-02-10 14:31 UTC
Labels: enhancement
