### ISSUE TITLE
metals formatting issue. 

### ISSUE THREAD

**Issue by abhishekvaid** [scalameta/metals-vscode#330] opened 2020-06-17 16:54 UTC
I keep getting pop up with creation of a new .scalafmt for formatting, but plugins doesn't create a new file. It's also not picking up the file which is already placed in the directory. 

Here are a few screenshots. 

When I have no .scalafmt.conf
<img width="1419" alt="Screen Shot 2020-06-17 at 10 21 52 PM" src="https://user-images.githubusercontent.com/2530932/84926516-21410800-b0e9-11ea-8ca1-d4f20e48ff02.png">

When I already have a .scalafmt.conf but metals is not picking it up. 
<img width="1440" alt="Screen Shot 2020-06-17 at 10 22 20 PM" src="https://user-images.githubusercontent.com/2530932/84926559-30c05100-b0e9-11ea-9c6d-eb853a957968.png">

My metals version is 1.9.0

**Comment by tgodzik** [comment] 2020-06-18 15:56
Thanks for reporting! Does it pick up the scalafmt file after reopening the window? I am unable to reproduce it locally, is there any particular project this doesn't work on or is it all projects on your machine?

**Comment by tgodzik** [comment] 2020-08-19 18:01
Cannot reproduce the issue, closing it for now. Let me know if you are able to find a reproducible scenario!

**Closed by tgodzik** 2020-08-19 18:01 UTC
Labels: neeeds more information
