### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bha6kar** [scalameta/metals-vscode#314] opened 2020-06-01 09:04 UTC
- Issue Type: `Performance`
- Extension Name: `metals`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\BhaskarSaikia\
[scalameta.metals-unresponsive.cpuprofile.txt](https://github.com/scalameta/metals-vscode/files/4710384/scalameta.metals-unresponsive.cpuprofile.txt)
scalameta.metals-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tgodzik** [comment] 2020-06-01 18:02
Thanks for reporting! What seems to an issue here? I see that some time is spent on locating javaHome, but that is done only once, so it shouldn't really be a problem. And the overall time doesn't seem to be that bad. I haven't noticed any unresponsiveness recently and the plugin itself doesn't do that much, so it's rather unexpected that it would cause any issues.

What prompted you to file the issue? Was is automated VS Code thing or did you notice any particular slowness yourself?

**Comment by bha6kar** [comment] 2020-06-05 18:59
Yes in my case both vscode by itself prompted for  this and metals break my project maybe project is too big that’s why 
As I use bloop in cmd that works fine but vscode metals struggle to compile

**Comment by tgodzik** [comment] 2020-06-08 10:11
If Bloop in console works then Metals should work as well, since we just invoke Bloop in a very similar way. The problem is that I do not see anything in the vscode log here, so I am not entirely sure why it reported performance problems. 

If Metals itself is working slowly it's much more likely that it's related to the server, which runs separate from VS Code extension in a JVM. Do you see anything in `.metals/metals.log` that might indicate a problem? There should be some timings especially related to indexing workspace.

Some questions that might help us out a bit:
1. How are the performance problems surfacing? 
2. What is working slow in the workspace? 
3. How large is the project?

The way we could approach it is:
- if it's an open source project then I could try to take a look at it with a profiler to figure out what's going on
- otherwise you could try to take a jstack of the Metals server JVM to see what it's hanging on
- or more advanced you could try the [https://github.com/jvm-profiling-tools/async-profiler](profiler) yourself (only for advanced users)

**Comment by tgodzik** [comment] 2020-06-25 13:57
Closing this until we get more information.I am unable to reproduce any such scenario.

**Closed by tgodzik** 2020-06-25 13:57 UTC
