### ISSUE TITLE
Starting Metals extension mutates workspace settings.json 

### ISSUE THREAD

**Issue by jvilk-stripe** [scalameta/metals-vscode#411] opened 2020-09-16 19:38 UTC
**Describe the bug**

**To Reproduce**
1. Install the Metals VS Code extension.
2. Open a folder with a .vscode/settings.json
3. Open a scala file to cause Metals to start running
4. Notice that `.vscode/settings.json` now contains the following setting:

```
"files.watcherExclude": {
    "**/target": true
  }
```

**Expected behavior**

Extension does not mutate workspace settings. No extension should ever mutate a workspace's settings. These are potentially shared between multiple users.

**Screenshots**

N/A

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: Whichever version the extension installs

**Additional context**
This is a frustrating issue for users of this extension who work in a repository with many users. When they create pull requests for a change, they have to ignore the changes to settings.json that this extension makes.

Why is Metals making this change to workspace VS Code configs?

**Search terms**

settings watching files Visual Studio Code VS Code settings.json workspace settings configuration

**Comment by gabro** [comment] 2020-09-23 06:47
Transferred this to vscode-metals since it's vscode-specific

**Comment by bursauxa** [comment] 2020-12-14 13:54
Sharing configuration from the .vscode folder (i.e. committing it to repository) is a pretty standard thing to do to set up things like run configurations. I would even go as far as saying it is designed as such, because for instance the tasks file defines OS-specific properties (being Windows, Linux or Mac) to allow running some tasks differently based on environment, which of course would make no sense if this file was not supposed to be shared.

In the case of the settings file I agree there is room for debate, but generally speaking it feels adequate for build-related things (mostly folders to exclude - not just from the watcher, but also from view and/or search). UI settings are the problematic ones, but they are usually user-level and not workspace-level, so should not leak into your shared settings. Of course, if an individual wants to have one project in red font and the other in green font, then it will not be possible... Hence the room for debate.

**Comment by tillig** [comment] 2021-11-13 18:40
Seems like this happens for almost every project recently, even if I don't open a Scala file. It doesn't look like this extension actually waits for any sort of activation, it's just active all the time.

In a .NET Core project - no hints of anything Java or Scala - just opening the workspace gets me the `.metals` folder, the update to `settings.json`, and a log at `null\scalameta\metals\cache\global.log` that I need to make sure is ignored.

Here's what shows up in the Output window for Metals:

```text
Java home: C:\Users\tillig\.jabba\jdk\adopt@1.11.0-11
Metals version: 0.10.9
2021.11.13 10:37:06 INFO  logging to file C:\dev\Autofac.AspNetCore.Multitenant\.metals\metals.log
2021.11.13 10:37:06 INFO  Started: Metals version 0.10.9 in workspace 'C:\dev\Autofac.AspNetCore.Multitenant' for client Visual Studio Code 1.62.2.
2021.11.13 10:37:10 INFO  time: initialize in 3.71s
Initializing Scala Debugger
2021.11.13 10:37:11 INFO  Flyway Community Edition 8.0.2 by Redgate
2021.11.13 10:37:11 INFO  Database: jdbc:h2:file:C:\dev\Autofac.AspNetCore.Multitenant\.metals\metals (H2 1.4)
2021.11.13 10:37:11 INFO  Successfully validated 3 migrations (execution time 00:00.049s)
2021.11.13 10:37:11 INFO  Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2021.11.13 10:37:11 INFO  Current version of schema "PUBLIC": << Empty Schema >>
2021.11.13 10:37:11 INFO  Migrating schema "PUBLIC" to version "1 - Create tables"
2021.11.13 10:37:11 INFO  Migrating schema "PUBLIC" to version "2 - Server discovery"
2021.11.13 10:37:11 INFO  Migrating schema "PUBLIC" to version "3 - Jar symbols"
2021.11.13 10:37:11 INFO  Successfully applied 3 migrations to schema "PUBLIC", now at version v3 (execution time 00:00.252s)
2021.11.13 10:37:11 WARN  Build server is not auto-connectable.
2021.11.13 10:37:11 WARN  no build tool detected in workspace 'C:\dev\Autofac.AspNetCore.Multitenant'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
```

I'm basically going to have to run with this extension specifically disabled unless I know I'll be working with a Scala project. It'd be nice if this extra cruft didn't just show up on unrelated projects.

**Comment by tgodzik** [comment] 2021-11-15 10:35
> Seems like this happens for almost every project recently, even if I don't open a Scala file. It doesn't look like this extension actually waits for any sort of activation, it's just active all the time.

Does it happen even on small projects?

The activation events are declared as following:
```
"activationEvents": [
    "onCommand:metals.new-scala-project",
    "onDebugResolve:scala",
    "onLanguage:scala",
    "workspaceContains:build.sbt",
    "workspaceContains:build.sc",
    "workspaceContains:project/build.properties",
    "workspaceContains:src/main/scala",
    "workspaceContains:*/src/main/scala",
    "workspaceContains:*/*/src/main/scala"
  ],
```

Unfortunately, `workspaceContains` will activate the extension in case of timeout, which is an issue within VS Code.
You can check in the extension host logs to see why the extension got activated.

**Comment by tillig** [comment] 2021-11-15 15:29
What I'm seeing is this:

`[2021-11-15 07:12:52.169] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals, startup: false, activationEvent: 'onLanguage:scala'`

But I'm seeing it in C#/.NET projects. I'm not sure _why_ it thinks there's Scala in there.

However, I'm realizing some possibly related things:

- If you visit the extension's _page_ in the marketplace - like if you look at extensions, show `@installed`, then look at the page for the Metals extension... it _activates the extension_. Even if it's not a Scala project.
- I don't have Java on all of my machines and the one I was on yesterday doesn't have it installed (no need, working on .NET). I was getting prompted to set up Java (for some reason) and I wonder if just that was also activating the Metals extension somehow indirectly. I'll have to look at that machine when I get time.

Seems like the extension shouldn't be activated if you just look at its page in the extension marketplace thing. I'll see about filing a VS Code bug for that.

**Comment by tillig** [comment] 2021-11-24 16:10
It just started on another .NET project and the extension host log message is:

`[2021-11-24 08:05:33.446] [exthost] [info] ExtensionService#_doActivateExtension scalameta.metals, startup: true, activationEvent: 'workspaceContainsTimeout:*/src/main/scala,*/*/src/main/scala'`

I'm not sure if that means it timed out looking for Scala code and decided that, by default, that means it should turn on or what. However, there's no `src/main/scala` anywhere in this project - it's all .NET.

**Comment by gabro** [comment] 2021-11-24 17:01
@tillig that's unfortunately the case: it times out searching those paths in the workspace and then it decides to activate the extension anyway. I'm afraid there's little we can do on the extension side :/

**Comment by tgodzik** [comment] 2021-11-24 17:06
It seems that this will be fixed in the next VS Code version finally :tada:  - https://github.com/microsoft/vscode/issues/73656#issuecomment-973880681

**Comment by tgodzik** [comment] 2022-01-20 15:43
Closing this as mutating `settings.json` is expected and done in a lot of different extensions.

**Closed by tgodzik** 2022-01-20 15:43 UTC

**Comment by dcm** [comment] 2022-04-11 03:37
This is incredibly annoying. Other extensions will add things to settings.json. Yours completely overwrites settings.json. This is not done by any other extensions, and is absolutely unexpected.

**Comment by kpodsiad** [comment] 2022-04-11 05:42
Hi @dcm, thanks for sharing your problem with us.
Could you provide an example or be more specific about `Yours completely overwrites settings.json`? IIRC we only add `files.watcherExclude` property, the rest of the settings should remain untouched. 
I checked now and our changes to the settings.json` are minimal and Metals didn't overwrite the file so reproduction or some example would be extremely useful for us.
