### ISSUE TITLE
Can't run java 21 via code lens / debug

### ISSUE THREAD

**Issue by rochala** [scalameta/metals-vscode#1435] opened 2023-10-20 13:47 UTC
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

```scala
//> using scala 3
//> using jvm 21

@main def hello =
  val x: com.sun.source.tree.AnyPatternTree = ???
```

<details open>
  <summary>Error log</summary>

```
 *  Executing task: /"opt"/"homebrew"/"Cellar"/"openjdk@17"/"17.0.7"/"libexec"/"openjdk.jdk"/"Contents"/"Home"/"bin"/"java"  -classpath "/Users/jrochala/Projects/scala-cli-playground/.metals/.tmp/classpath_27F172492313EEA3967CB8BD059EAD98.jar" hello  

Error: LinkageError occurred while loading main class hello
        java.lang.UnsupportedClassVersionError: hello has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

 *  The terminal process "/etc/profiles/per-user/jrochala/bin/zsh '-l', '-c', '/"opt"/"homebrew"/"Cellar"/"openjdk@17"/"17.0.7"/"libexec"/"openjdk.jdk"/"Contents"/"Home"/"bin"/"java"  -classpath "/Users/jrochala/Projects/scala-cli-playground/.metals/.tmp/classpath_27F172492313EEA3967CB8BD059EAD98.jar" hello '" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 

```
</details>

**Expected behavior**

It should work

**Screenshots**

**Installation:**

- Operating system: macOS/Windows/Linux
- VSCode version: 
- VSCode extension version:
- Metals version: 1.1.0

**Additional context**

Metals uses java from classpath to run the code. It should use the same java that is defined in Scala-CLI using directive

**Search terms**

**Comment by tgodzik** [comment] 2023-10-23 14:40
Duplicate of https://github.com/scalameta/metals-vscode/issues/1433

**Closed by tgodzik** 2023-10-23 14:40 UTC
